---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
##library(readxl)
##library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>

.size60[.center[
Working on the Final Paper
]]

<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???

1. Review submitted cases
    - https://docs.google.com/document/d/1iNYRC6BRI8WDdXoAETCy3OTeaBFQ6w2cBV9CZ0Xl6JU/edit?usp=sharing

<br>




---

class: middle, slideblue

.center[.size50[**Final Paper Prompt**]]

.size35[Write a report analyzing a specific policy action taken by a state or a non-state actor meant to reduce the occurrence or severity of terrorism in a single country.

- Analyze Terrorism Data (GTD and EDTG)
- Analyze Political Violence Data (CIRIGHTS and PTS)

Does the evidence indicate that these interventions have reduced the frequency or scale of attacks? Have these interventions impacted citizens' experiences of political violence in the state?]

???

### Questions on the final paper?



---

class: middle, slideblue

.size70[**For Today**]

.size50[
Bring to class a recent example of a specific policy action taken by a state or a non-state actor meant to reduce the occurrence or severity of terrorism in a single country.]

???

### Everybody ready to go with this?




---

class: middle, slideblue

.size70[**Proposed Cases**]

.size50[
1. What country is being targeted?

2. Who made the policy?

3. What is the policy?

4. Why did you select this policy?
]

???

Let's hear your proposed cases!

As you listen think about how you would write their paper and be ready to give feedback!




---

class: middle, slideblue

.size70[**For Monday**]

.size50[
Bring the data we need to start analyzing the case you've selected in class on Monday
- PTS,
- CIRIGHTS,
- GTD, 
- EDTG
]

???
















