---
format: revealjs
---

## Today's Agenda {background-image="Images/00-Leviathan_Cover_55.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
```

<br>

**IV. How do we make political violence less likely?**

<br>

- Identifying institutional vulnerabilities in the US

<br>

::: r-stack
Justin Leinaweaver (Fall 2025)
:::

::: notes

Prep for Class

1. Review submissions on Canvas

<br>

Today we shift into the end of our semester with a focus on what we can do to make political violence less likely in our community.

- Essentially, answering that question represents your final work in this class.

<br>

**SLIDE**: IDEA eval reminder

:::



## Course Evaluations (IDEA) {background-image="Images/00-Leviathan_Cover_55.png" .center}

<br>

::: {.r-fit-text}
[https://drury.campuslabs.com/eval-home/](https://drury.campuslabs.com/eval-home/)
:::

::: notes

REMEMBER, IFF everyone in class submits their evals for this class I will give everyone EC on the final grade!

- So, get em done!

<br>

**SLIDE**: For today

:::




## For Today {background-image="Images/00-Leviathan_Cover_55.png" .center}

<br>

What are the institutional designs that currently exist in the US that make us vulnerable to political violence? 

In other words, what are the aspects of our community that create or allow for acts of political violence to occur?

- These can be formal institutions (laws, policies, etc) or informal ones (norms, customs, etc).

::: notes

For today I asked each of you to reflect on our threats in order to identify ONE institutional design in our society that makes us vulnerable to political violence.

- **How did this go?**

<br>

To begin, I want each of you to review all of the submissions

- Make sure you are clear on the institutions and vulnerabilities being suggested by your classmates

- Let's use this time to get clarifications

- Go!

<br>

*Split class into four groups*

- Go sit with your group and claim some space on the board!

<br>

Ok, let's layer some comparative analyses on top of this data!

- **SLIDE**: Prompt 1

<br>

Canvas Assignment: Identifying Vulnerabilities

What is ONE institutional design that currently exists in the US that makes us vulnerable to political violence? In other words, what is an aspect of our community that creates or allows for acts of political violence to occur? This can be a formal institution (e.g. laws, policies, regulations, constitutional provisions, etc) or an informal one (e.g. norms, customs, etc).

Please try to avoid exact overlap with the other submitted cases (e.g. an institution x a specific vulnerability). Multiple people can submit the same institution or the same vulnerability, but only one can claim a specific pairing.

Please note, I am not asking you to make the argument that your selected institution must change. I simply want us to identify the interactions between institutional design and risk.

1. What is the specific institution you are focused on? (explain your selection and cite evidence it exists)
2. How does that specific institution create a vulnerability to political violence? (explain the causal mechanism as clearly as you can, 3-5 sentences)
3. Submit a piece of evidence that illustrates this dynamic in action (APA citation and explanation of the evidence)

:::



## {background-image="Images/14_3-Capitol_Building_v3.png"}

**Classifying our Institutional Vulnerabilities**

1. What are the FIVE "most serious" vulnerabilities? 

::: notes

I'm going to ask you to classify the cases three times on the board

- FIRST, I want your group to select the FIVE most serious vulnerabilities

- e.g. those most responsible for our vulnerability to political violence

<br>

Think of this as what institutions create the most openings or incentives for political violence in our society?

- Go!

<br>

**SLIDE**: Next classifications

:::



## {background-image="Images/14_3-Capitol_Building_v3.png"}

**Classifying our Institutional Vulnerabilities**

1. What are the FIVE "most serious" vulnerabilities? 

2. What are the FIVE "easiest" vulnerabilities to address? 

3. What are the FIVE "hardest" vulnerabilities to address? 


::: notes

Ok, two more lists

- What are the five vulnerabilities that would be easiest to address?

- What are the five vulnerabilities that would be hardest to address?

- Go!

<br>

Groups, present your analysis of the US

- What institutional vulnerabilities do we have and how hard woulf they be to address?

- *PRESENT and DISCUSS each*

:::



## {background-image="Images/14_3-Capitol_Building_v3.png" .center}

### **Does the institutional design of United States make us vulnerable to political violence?**

::: notes

Let's talk big picture takeaways.

<br>

**Overall, does the institutional design of the US make us vulnerable to political violence? Why or why not?**

<br>

**Are we convinced that we could eliminate this vulnerability using purely institutional fixes? Why or why not?**

<br>

**What are the drawbacks to using institutional rules to reduce the vulnerabilities we face?**

- **Are they worth the reductions in "freedom" they might require? Why or why not?**

<br>

**SLIDE**: With all of this in mind, here's the prompt for your final paper

:::



## {background-image="Images/00-Leviathan_Cover_55.png" .center}

**Paper 3: Political Violence Research Proposal**

<br>

Convert your intuitions about the institutional vulnerabilities in the US system into a research proposal. 

::: notes

Your final paper for this class will be a research proposal like the exercise we've been doing in class the last two weeks

- The idea is reframe your intuitions as an opportunity to test them with real world evidence

<br>

Proposals are due by the end of our class final exam window

- Dec 8th, 12:20pm

- NO LATE PAPERS ACCEPTED

<br>

**SLIDE**: Details

:::



## {background-image="Images/00-Leviathan_Cover_55.png" .center}

**Paper 3: Political Violence Research Proposal**

<br>

This should be written as an argument paper that advances the specifics of your proposal as its thesis statement with a body focused on three specific premises:

1. Your research question is important, can be answered and its answer improves our understanding of the world,

2. Your proposed answer to the question (theory) is clear and logical (with a DAG represented as a figure in the paper), and

3. You can explain to the reader the kinds of data you would need to test your theory with real-world evidence.


::: notes

Think of this like any other three premise argument paper you've written for me:

- Your first premise focuses on selling the reader on your RQ,

- Your second premise explains your theoretical answer to the question, and

- Your third premise talks through the data needs for the project

<br>

Put all together you have an argument that this research project is worth investing our time and money into!

<br>

**Questions on the assignment?**

<br>

**SLIDE**: Let's set your first goal for next class

:::



## For Next Class {background-image="Images/00-Leviathan_Cover_55.png" .center}

<br>

What is your research question and why is it a "good" one?

- It can be answered

- It improves our understanding of the world, and

- It is important we answer it (with evidence)


::: notes

**Questions on the assignment?**

<br>

Canvas Assignment: Developing your Research Proposal: Research Question (RQ)

1. What is your proposed research question?
2. Explain why you are confident this question "can be answered" with data (meaning it is not normative or opinion based, 2+ sentences)
3. Explain how this RQ "improves our understanding of the world" (meaning it helps us think theoretically about why things happen, 3+ sentences)
4. Provide AT LEAST one piece of evidence that this is an important question to answer (APA citation and 2+ sentences explaning how the evidence makes the importance argument)


:::

