---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
##library(readxl)
##library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: middle, slideblue

# IDEA Course Evaluations

<br>

## Direct Link:

.size35[
https://drury.campuslabs.com/eval-home/direct/2857263
]

???

10 minutes for the evals

I also sent the link out by email



---

class: slideblue

.size70[**Today's Agenda**]

<br>

.size55[
Final Paper Work

- Working with our data: PTS, CIRIGHTS, GTD and EDTG
]


<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???

Today: Review the data and collaborate on ideas to visualize the data




---

class: middle, slideblue

.center[.size50[**Final Paper Prompt**]]

.size35[Write a report analyzing a specific policy action taken by a state or a non-state actor meant to reduce the occurrence or severity of terrorism in a single country.

- Analyze Terrorism Data (GTD and EDTG)
- Analyze Political Violence Data (CIRIGHTS and PTS)

Does the evidence indicate that these interventions have reduced the frequency or scale of attacks? Have these interventions impacted citizens' experiences of political violence in the state?]

???

### Questions on the final paper?




---

class: middle, slideblue

.size70[**For Today**]

.size50[
Bring the data we need to start analyzing the case you've selected in class on Monday
- PTS,
- CIRIGHTS,
- GTD, 
- EDTG
]

???



---

class: middle, slideblue

.size70[**For Wednesday**]

.size50[
What other evidence do you need to make this argument? 

- Go find it and bring to class!
]

???




