---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
##library(readxl)
##library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>

.size65[
Work on Final Paper Projects
]

<br>

.center[.size40[
  Justin Leinaweaver (Spring 2022)
]]

???



---

class: middle, slideblue

.center[.size50[**Final Paper Prompt**]]

.size35[Write a report analyzing a specific policy action taken by a state or a non-state actor meant to reduce the occurrence or severity of terrorism in a single country.

- Analyze Terrorism Data (GTD and EDTG)
- Analyze Political Violence Data (CIRIGHTS and PTS)

Does the evidence indicate that these interventions have reduced the frequency or scale of attacks? Have these interventions impacted citizens' experiences of political violence in the state?]

???

### Questions on the final paper?




---

class: middle, slideblue

.size70[**For Today**]

.size50[
What other evidence do you need to make this argument? 

- Go find it and bring to class!
]

???

### Everybody ready to go with this?




---

class: middle, slideblue

# The Key Analytical Questions
.size40[
1. Does the evidence indicate that these interventions have reduced the frequency or scale of attacks? 

2. Have these interventions impacted citizens' experiences of political violence in the state?
]

???

Here the two key analytical questions in the paper prompt.

--

.size40[
.center[**Do you have enough evidence to answer these two questions with some certainty?**]
]

???

<br>

<br>

Your job today is to present your answer to these two questions and the evidence you have so far to classmates.

Are they convinced you have a clear answer and sufficient evidence to support it?


